language: node_js
node_js:
  - "lts/*"

dist: trusty
addons:
  chrome: stable
before_install:
  - npm install -g @lhci/cli@0.3.x
script: 
  - npm run clean
  - npm run lint
  - npm run build
after_success:
  - npx http-server -p 8080 ./public & >> dev/null
  - lhci healthcheck --fatal
  - lhci autorun
  