version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - lint
jobs:
  lint:
    executor: node/default
    steps:
      - checkout
      - node:
        steps:
          - run: npm ci
      - run: npm run lint
